// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: svm_predictor.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "svm_predictor.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* SVMPredictorConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SVMPredictorConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_svm_5fpredictor_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_svm_5fpredictor_2eproto() {
  protobuf_AddDesc_svm_5fpredictor_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "svm_predictor.proto");
  GOOGLE_CHECK(file != NULL);
  SVMPredictorConfig_descriptor_ = file->message_type(0);
  static const int SVMPredictorConfig_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SVMPredictorConfig, model_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SVMPredictorConfig, resize_height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SVMPredictorConfig, resize_width_),
  };
  SVMPredictorConfig_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      SVMPredictorConfig_descriptor_,
      SVMPredictorConfig::default_instance_,
      SVMPredictorConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SVMPredictorConfig, _has_bits_[0]),
      -1,
      -1,
      sizeof(SVMPredictorConfig),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SVMPredictorConfig, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_svm_5fpredictor_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      SVMPredictorConfig_descriptor_, &SVMPredictorConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_svm_5fpredictor_2eproto() {
  delete SVMPredictorConfig::default_instance_;
  delete SVMPredictorConfig_reflection_;
}

void protobuf_AddDesc_svm_5fpredictor_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_svm_5fpredictor_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023svm_predictor.proto\"U\n\022SVMPredictorCon"
    "fig\022\022\n\nmodel_name\030\001 \002(\t\022\025\n\rresize_height"
    "\030\002 \002(\005\022\024\n\014resize_width\030\003 \002(\005", 108);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "svm_predictor.proto", &protobuf_RegisterTypes);
  SVMPredictorConfig::default_instance_ = new SVMPredictorConfig();
  SVMPredictorConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_svm_5fpredictor_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_svm_5fpredictor_2eproto {
  StaticDescriptorInitializer_svm_5fpredictor_2eproto() {
    protobuf_AddDesc_svm_5fpredictor_2eproto();
  }
} static_descriptor_initializer_svm_5fpredictor_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SVMPredictorConfig::kModelNameFieldNumber;
const int SVMPredictorConfig::kResizeHeightFieldNumber;
const int SVMPredictorConfig::kResizeWidthFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SVMPredictorConfig::SVMPredictorConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SVMPredictorConfig)
}

void SVMPredictorConfig::InitAsDefaultInstance() {
}

SVMPredictorConfig::SVMPredictorConfig(const SVMPredictorConfig& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SVMPredictorConfig)
}

void SVMPredictorConfig::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  model_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  resize_height_ = 0;
  resize_width_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SVMPredictorConfig::~SVMPredictorConfig() {
  // @@protoc_insertion_point(destructor:SVMPredictorConfig)
  SharedDtor();
}

void SVMPredictorConfig::SharedDtor() {
  model_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void SVMPredictorConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SVMPredictorConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SVMPredictorConfig_descriptor_;
}

const SVMPredictorConfig& SVMPredictorConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_svm_5fpredictor_2eproto();
  return *default_instance_;
}

SVMPredictorConfig* SVMPredictorConfig::default_instance_ = NULL;

SVMPredictorConfig* SVMPredictorConfig::New(::google::protobuf::Arena* arena) const {
  SVMPredictorConfig* n = new SVMPredictorConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SVMPredictorConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:SVMPredictorConfig)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(SVMPredictorConfig, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<SVMPredictorConfig*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 7u) {
    ZR_(resize_height_, resize_width_);
    if (has_model_name()) {
      model_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool SVMPredictorConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SVMPredictorConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string model_name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_model_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->model_name().data(), this->model_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "SVMPredictorConfig.model_name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_resize_height;
        break;
      }

      // required int32 resize_height = 2;
      case 2: {
        if (tag == 16) {
         parse_resize_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &resize_height_)));
          set_has_resize_height();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_resize_width;
        break;
      }

      // required int32 resize_width = 3;
      case 3: {
        if (tag == 24) {
         parse_resize_width:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &resize_width_)));
          set_has_resize_width();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SVMPredictorConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SVMPredictorConfig)
  return false;
#undef DO_
}

void SVMPredictorConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SVMPredictorConfig)
  // required string model_name = 1;
  if (has_model_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->model_name().data(), this->model_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "SVMPredictorConfig.model_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->model_name(), output);
  }

  // required int32 resize_height = 2;
  if (has_resize_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->resize_height(), output);
  }

  // required int32 resize_width = 3;
  if (has_resize_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->resize_width(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:SVMPredictorConfig)
}

::google::protobuf::uint8* SVMPredictorConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SVMPredictorConfig)
  // required string model_name = 1;
  if (has_model_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->model_name().data(), this->model_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "SVMPredictorConfig.model_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->model_name(), target);
  }

  // required int32 resize_height = 2;
  if (has_resize_height()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->resize_height(), target);
  }

  // required int32 resize_width = 3;
  if (has_resize_width()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->resize_width(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SVMPredictorConfig)
  return target;
}

int SVMPredictorConfig::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:SVMPredictorConfig)
  int total_size = 0;

  if (has_model_name()) {
    // required string model_name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->model_name());
  }

  if (has_resize_height()) {
    // required int32 resize_height = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->resize_height());
  }

  if (has_resize_width()) {
    // required int32 resize_width = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->resize_width());
  }

  return total_size;
}
int SVMPredictorConfig::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:SVMPredictorConfig)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required string model_name = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->model_name());

    // required int32 resize_height = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->resize_height());

    // required int32 resize_width = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->resize_width());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SVMPredictorConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SVMPredictorConfig)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const SVMPredictorConfig* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const SVMPredictorConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SVMPredictorConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SVMPredictorConfig)
    MergeFrom(*source);
  }
}

void SVMPredictorConfig::MergeFrom(const SVMPredictorConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SVMPredictorConfig)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_model_name()) {
      set_has_model_name();
      model_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.model_name_);
    }
    if (from.has_resize_height()) {
      set_resize_height(from.resize_height());
    }
    if (from.has_resize_width()) {
      set_resize_width(from.resize_width());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void SVMPredictorConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SVMPredictorConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SVMPredictorConfig::CopyFrom(const SVMPredictorConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SVMPredictorConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SVMPredictorConfig::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void SVMPredictorConfig::Swap(SVMPredictorConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SVMPredictorConfig::InternalSwap(SVMPredictorConfig* other) {
  model_name_.Swap(&other->model_name_);
  std::swap(resize_height_, other->resize_height_);
  std::swap(resize_width_, other->resize_width_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SVMPredictorConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SVMPredictorConfig_descriptor_;
  metadata.reflection = SVMPredictorConfig_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SVMPredictorConfig

// required string model_name = 1;
bool SVMPredictorConfig::has_model_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void SVMPredictorConfig::set_has_model_name() {
  _has_bits_[0] |= 0x00000001u;
}
void SVMPredictorConfig::clear_has_model_name() {
  _has_bits_[0] &= ~0x00000001u;
}
void SVMPredictorConfig::clear_model_name() {
  model_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_model_name();
}
 const ::std::string& SVMPredictorConfig::model_name() const {
  // @@protoc_insertion_point(field_get:SVMPredictorConfig.model_name)
  return model_name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SVMPredictorConfig::set_model_name(const ::std::string& value) {
  set_has_model_name();
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SVMPredictorConfig.model_name)
}
 void SVMPredictorConfig::set_model_name(const char* value) {
  set_has_model_name();
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SVMPredictorConfig.model_name)
}
 void SVMPredictorConfig::set_model_name(const char* value, size_t size) {
  set_has_model_name();
  model_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SVMPredictorConfig.model_name)
}
 ::std::string* SVMPredictorConfig::mutable_model_name() {
  set_has_model_name();
  // @@protoc_insertion_point(field_mutable:SVMPredictorConfig.model_name)
  return model_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* SVMPredictorConfig::release_model_name() {
  // @@protoc_insertion_point(field_release:SVMPredictorConfig.model_name)
  clear_has_model_name();
  return model_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void SVMPredictorConfig::set_allocated_model_name(::std::string* model_name) {
  if (model_name != NULL) {
    set_has_model_name();
  } else {
    clear_has_model_name();
  }
  model_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model_name);
  // @@protoc_insertion_point(field_set_allocated:SVMPredictorConfig.model_name)
}

// required int32 resize_height = 2;
bool SVMPredictorConfig::has_resize_height() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void SVMPredictorConfig::set_has_resize_height() {
  _has_bits_[0] |= 0x00000002u;
}
void SVMPredictorConfig::clear_has_resize_height() {
  _has_bits_[0] &= ~0x00000002u;
}
void SVMPredictorConfig::clear_resize_height() {
  resize_height_ = 0;
  clear_has_resize_height();
}
 ::google::protobuf::int32 SVMPredictorConfig::resize_height() const {
  // @@protoc_insertion_point(field_get:SVMPredictorConfig.resize_height)
  return resize_height_;
}
 void SVMPredictorConfig::set_resize_height(::google::protobuf::int32 value) {
  set_has_resize_height();
  resize_height_ = value;
  // @@protoc_insertion_point(field_set:SVMPredictorConfig.resize_height)
}

// required int32 resize_width = 3;
bool SVMPredictorConfig::has_resize_width() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void SVMPredictorConfig::set_has_resize_width() {
  _has_bits_[0] |= 0x00000004u;
}
void SVMPredictorConfig::clear_has_resize_width() {
  _has_bits_[0] &= ~0x00000004u;
}
void SVMPredictorConfig::clear_resize_width() {
  resize_width_ = 0;
  clear_has_resize_width();
}
 ::google::protobuf::int32 SVMPredictorConfig::resize_width() const {
  // @@protoc_insertion_point(field_get:SVMPredictorConfig.resize_width)
  return resize_width_;
}
 void SVMPredictorConfig::set_resize_width(::google::protobuf::int32 value) {
  set_has_resize_width();
  resize_width_ = value;
  // @@protoc_insertion_point(field_set:SVMPredictorConfig.resize_width)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
